version: '3.8'

services:
  ollama:
    image: docker.io/ollama/ollama
    container_name: ollama
    networks:
      - matrixpod
    restart: always
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ./data/open-webui:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "127.0.0.1:3002:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data/open-webui:/app/backend/data
    networks:
      matrixpod:
        aliases:
          - ollama.local
    depends_on:
      - ollama

networks:
  matrixpod:
    external: true
    name: matrixpod

volumes:
  open-webui: {}
